export const ADD_TASKS = 'ADD_TASKS'
export const LIST_TASKS = 'LIST_TASKS'
export const SHOW_TASK = 'SHOW_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const SET_TASKS = 'SET_TASKS'

export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const COUNT = 'COUNT'
